INSERT INTO "composer" ("id", "name", "portrait", "epoch", "birth_date", "birth_place", "death_date", "death_place", "background_image", "short_description", "long_description") VALUES
                                                                                                                                                                                      (87,	'Johann Sebastian Bach',	'https://assets.openopus.org/portraits/12091447-1568084857.jpg',	'Baroque',	'1685-01-01 00:00:00',	'Eisenach, Germany',	'1750-01-01 00:00:00',	'Leipzig',	NULL,	'Johann Sebastian Bach (1685-1750) was a German composer and musician of the Baroque period. He is widely considered one of the greatest composers of all time, and his music is known for its complex harmonies, intricate counterpoint, and emotional depth.',	'Johann Sebastian Bach (1685-1750), the German composer, organist, harpsichordist, and violinist, is considered one of the greatest musical geniuses of all time. Born into a family of musicians, he was a child prodigy who mastered various instruments from an early age. By the age of 18, Bach had already established himself as an accomplished organist, holding several positions in prestigious churches. Throughout his lifetime, he served as a court musician for various German princes and noblemen, composing prolifically for a wide range of instruments and ensembles.

Bach''s music is characterized by its exceptional craftsmanship, complex harmonies, and intricate counterpoint. He developed new musical forms and techniques, pushing the boundaries of Baroque music to new heights. His works include the Brandenburg Concertos, the Goldberg Variations, the Well-Tempered Clavier, and the Mass in B Minor, all of which are regarded as masterpieces of Western classical music. Bach''s compositions are not only technically demanding but also deeply expressive, conveying a wide range of emotions and spirituality. Through his profound musical intellect and unwavering dedication to his craft, Bach created an enduring legacy that continues to inspire and awe musicians and audiences alike.

Bach''s influence on music history is immeasurable. He is considered the father of modern Western music, and his works have served as a model and inspiration for countless composers after him. Bach''s music is performed and studied worldwide, and his name remains synonymous with musical genius, creativity, and mastery.'),
                                                                                                                                                                                      (145,	'Ludwig van Beethoven',	'https://assets.openopus.org/portraits/55910756-1568084860.jpg',	'Early Romantic',	'1770-01-01 00:00:00',	'Bonn, Germany',	'1827-01-01 00:00:00',	'Vienna, Austria',	NULL,	'Ludwig van Beethoven, a German composer and pianist, is widely regarded as one of the greatest composers of all time. His music is known for its emotional depth, technical brilliance, and innovative approach to form and harmony.',	'Ludwig van Beethoven, the renowned German composer, was born in Bonn in 1770. His extraordinary musical talent emerged at an early age, and he received rigorous training from his father and other prominent musicians. By his early twenties, Beethoven had established himself as a virtuoso pianist and composer in Vienna, the musical capital of Europe. His compositions during this period, such as the "Pathétique" Sonata and the First Symphony, showcased his innovative approach to musical form and expression.

As Beethoven''s career progressed, he faced personal and professional challenges. He suffered from hearing loss, which gradually worsened to the point of near-deafness. Despite this adversity, he continued to compose prolifically, producing some of his most famous and enduring works. The "Eroica" Symphony, for instance, is a testament to his indomitable spirit and his commitment to expressing heroic ideals through music. Beethoven also explored the dramatic possibilities of opera in "Fidelio," creating a masterpiece that combines profound themes with soaring melodies.

Beethoven''s influence on Western classical music is immeasurable. His groundbreaking compositions expanded the boundaries of musical expression, introducing new levels of emotional intensity, rhythmic complexity, and structural sophistication. His legacy as one of the greatest composers of all time is firmly established, with works such as the Ninth Symphony, the "Emperor" Concerto, and the "Moonlight" Sonata continuing to inspire and captivate audiences worldwide.'),
                                                                                                                                                                                      (80,	'Johannes Brahms',	'https://assets.openopus.org/portraits/46443632-1568084867.jpg',	'Romantic',	'1833-01-01 00:00:00',	'Hamburg, Germany',	'1897-01-01 00:00:00',	'Vienna, Austria',	NULL,	'Johannes Brahms, renowned German composer and pianist, lived from 1833 to 1897. He was a leading figure of the Romantic era, known for his intricate compositions and technical mastery.',	'Johannes Brahms (1833-1897) was a towering figure in the Romantic era of classical music, known for his profound artistry, technical mastery, and enduring legacy. Born in Hamburg, Germany, to a poor family of musicians, Brahms displayed prodigious musical talent from an early age. He embarked on a career as a concert pianist and toured extensively, gaining recognition for his brilliant technique and expressive performances.

Throughout his life, Brahms remained dedicated to composing, producing a vast and diverse body of work that encompassed symphonies, concertos, chamber music, piano pieces, and choral works. His music is characterized by its structural rigor, lyrical melodies, and rich harmonic textures. Brahms drew inspiration from both classical traditions and folk music, creating a unique sound that blended elements of the past and present. His works are imbued with a profound sense of emotion, from serene beauty to dramatic grandeur, and have captivated audiences for generations.

As a composer, Brahms was influenced by the masters of the past, particularly Beethoven and Schumann. He also championed the work of his contemporaries, including Clara Schumann and Antonín Dvořák. Brahms''s influence on subsequent generations of composers was immense, and his music continues to be performed and studied around the world. His legacy as one of the greatest composers of all time is firmly established, and his music remains a testament to his genius and enduring artistic vision.'),
                                                                                                                                                                                      (152,	'Frédéric Chopin',	'https://assets.openopus.org/portraits/72753742-1568084874.jpg',	'Romantic',	'1810-01-01 00:00:00',	'Żelazowa Wola, Poland',	'1849-01-01 00:00:00',	'Paris, France',	NULL,	'Frédéric Chopin, a Polish composer and virtuoso pianist of the Romantic era, is renowned for his poetic and expressive compositions, particularly his nocturnes, études, and mazurkas. His distinctive style blended elements of classical and folk music, captivating audiences with its emotional intensity and melodic beauty.',	'Frédéric Chopin, born on March 1, 1810, in Zelazowa Wola, Poland, was a virtuoso pianist and composer who left an enduring legacy in the world of classical music. Renowned for his exceptional talent and profound emotional expression, Chopin is considered one of the greatest Romantic composers. His music is characterized by its exquisite lyricism, intricate melodies, and distinctive rhythms, which evoke a deep sense of longing, passion, and introspection. Despite his relatively short life, spanning only 39 years, Chopin''s contributions to the piano repertoire remain unparalleled, and his compositions continue to captivate audiences worldwide.

Chopin''s early musical education began under the guidance of his father, who was a teacher at the Warsaw Lyceum. At the age of 16, he enrolled at the Warsaw Conservatory, where he studied composition with Józef Elsner. Chopin''s natural talent and virtuosity quickly gained recognition, and he soon became a prominent figure in Warsaw''s musical circles. In 1830, following the November Uprising, Chopin left Poland for Vienna, where he established himself as a celebrated pianist and composer. He later moved to Paris in 1831, which became his home for the rest of his life.

Throughout his career, Chopin composed primarily for the piano. His works include numerous preludes, études, nocturnes, mazurkas, polonaises, and sonatas. Each composition showcased his mastery of the keyboard and his ability to convey a wide range of emotions through music. Chopin''s music is often described as introspective, melancholy, and romantic, reflecting his personal experiences and emotional struggles. Despite his frail health, which was affected by tuberculosis, Chopin continued to compose until the end of his life. His untimely death in 1849 was a profound loss to the world of music, leaving behind a legacy that continues to inspire and enchant generations of pianists and music lovers alike.'),
                                                                                                                                                                                      (105,	'Claude Debussy',	'https://assets.openopus.org/portraits/58875477-1568084877.jpg',	'Late Romantic',	'1862-01-01 00:00:00',	'Saint-Germain-en-Laye, France',	'1918-01-01 00:00:00',	'Paris',	NULL,	'Claude Debussy, a renowned French composer, revolutionized music in the late 19th and early 20th centuries. His impressionistic style, characterized by ethereal harmonies, evocative melodies, and innovative orchestrations, left an enduring legacy in the world of classical music.',	'Claude Debussy, a French composer born on August 22, 1862, was one of the most influential figures in the transition from the Romantic era to the 20th century. Known for his innovative use of harmony, rhythm, and orchestration, Debussy is widely regarded as the father of Impressionistic music.

Debussy''s compositions were characterized by their ethereal, evocative qualities, which evoked the sensations and emotions of nature and human experience. He employed shimmering textures, unresolved chords, and unconventional scales to create a unique and innovative sound world. Notable works include the orchestral suite "Prélude à l''après-midi d''un faune" (1894), the opera "Pelléas et Mélisande" (1902), and the piano pieces "Clair de Lune" and "Arabesque." Debussy''s influence extended beyond music, inspiring artists in other fields such as painting and literature.

Debussy''s life was marked by both personal triumphs and struggles. Despite recognition for his musical genius, he faced financial difficulties and health issues throughout his career. He died of cancer at the age of 55 on March 25, 1918, leaving behind a legacy that continues to captivate and inspire musicians and music lovers worldwide. His groundbreaking compositions and unique musical language have cemented his place as one of the most important and influential composers of all time.'),
                                                                                                                                                                                      (189,	'Antonín Dvořák',	'https://assets.openopus.org/portraits/32988185-1568084888.jpg',	'Romantic',	'1841-01-01 00:00:00',	'Nelahozeves, Czech Republic',	'1904-01-01 00:00:00',	'Prague, Czech Republic',	NULL,	'Antonín Dvořák was a Czech composer known for his contributions to classical music. He is celebrated for his lyrical melodies, rich harmonies, and masterful use of folk music elements in his compositions. His most famous works include the "New World Symphony" and the "Slavic Dances."',	'Antonín Dvořák, born in 1841 in Nelahozeves, Bohemia (part of the present-day Czech Republic), was a renowned Czech composer renowned for his profound mastery of melody, harmony, and orchestration. His music, deeply rooted in Bohemian folk traditions, beautifully blended Romantic and Classical elements, creating an enchanting and evocative sound.

Throughout his illustrious career, Dvořák composed a vast and diverse body of works that showcased his exceptional versatility. His nine symphonies, including the beloved "New World Symphony," stand as testaments to his brilliance in orchestral composition. Each symphony showcased Dvořák''s unique ability to weave intricate classical structures with vibrant folk-inspired melodies, resulting in music that was both sophisticated and accessible. Beyond his symphonies, Dvořák''s extensive catalog includes concertos, chamber music, choral works, and operas. His "Cello Concerto in B Minor" remains one of the most revered and technically demanding concertos in the cello repertoire, while his opera "Rusalka" has become a beloved classic in Czech opera houses.

Dvořák''s music enjoyed immense popularity during his lifetime and continues to be celebrated worldwide. His compositions have been praised for their emotional depth, rhythmic vitality, and masterful orchestration. As a teacher and mentor, Dvořák played a significant role in the development of subsequent generations of Czech composers, including Leoš Janáček and Josef Suk. His legacy as one of the greatest composers of the 19th century endures through the timeless beauty and enduring appeal of his music, which continues to captivate and inspire audiences around the globe.'),
                                                                                                                                                                                      (136,	'George Gershwin',	'https://assets.openopus.org/portraits/15396024-1568084900.jpg',	'20th Century',	'1898-01-01 00:00:00',	'Brooklyn, New York, U.S.',	'1937-01-01 00:00:00',	'Beverly Hills, California',	NULL,	'George Gershwin (1898-1937) was an American composer and pianist known for his innovative and influential contributions to both classical and popular music. He is widely considered one of the greatest American composers of the 20th century.',	'George Gershwin, an American musical virtuoso, was born in Brooklyn, New York, on September 26, 1898. Known for his prodigious talent in capturing the rhythms and melodies of American life, he left an indelible mark on the world of jazz, classical music, and popular song. Gershwin''s musical journey began at a young age, influenced by the bustling streets and vibrant music halls of his neighborhood. With an exceptional ear and natural ability at the piano, he immersed himself in the emerging jazz scene of the 1920s.

Gershwin''s unique style blended elements of classical music, jazz, and popular song, creating a distinctive sound that captivated audiences. His iconic compositions, such as "Rhapsody in Blue" and "An American in Paris," showcased his masterful combination of intricate orchestration and infectious rhythms. Gershwin''s collaborations with his brother Ira, a gifted lyricist, further enhanced his work, producing timeless songs like "Summertime," "Embraceable You," and "I Got Rhythm." Gershwin''s influence extended beyond the boundaries of jazz, as he ventured into the world of opera as well. His opera "Porgy and Bess," based on DuBose Heyward''s novel, became a groundbreaking work that explored themes of race and love in a powerful and moving way.

Tragically, Gershwin''s life was cut short at the height of his career. In 1937, at the age of 38, he passed away from a brain tumor. Despite his untimely demise, Gershwin''s legacy continues to live on, as his music continues to inspire and entertain generations of listeners. He is widely regarded as one of America''s greatest composers, and his contributions to the world of music have cemented his place as a timeless icon.'),
                                                                                                                                                                                      (67,	'George Frideric Handel',	'https://assets.openopus.org/portraits/59133744-1568084908.jpg',	'Baroque',	'1685-01-01 00:00:00',	'Halle, Duchy of Magdeburg, Holy Roman Empire',	'1759-01-01 00:00:00',	'London, England',	NULL,	'George Frideric Handel, a renowned German-born composer of the Baroque period, is celebrated for his exceptional operas, oratorios, and instrumental works. His masterpieces, including "Messiah" and "Water Music," showcase his extraordinary talent and continue to captivate audiences worldwide.',	'George Frideric Handel (1685-1759) was a German-born Baroque composer, widely considered one of the greatest composers of all time. He was renowned for his exceptional talent in composing operas, oratorios, concertos, and instrumental music. Handel''s early musical education in Germany laid the foundation for his exceptional skills as a keyboard player, organist, and composer. Renowned for his innovative and expressive style, Handel masterfully blended elements of Italian, German, and English musical traditions. Some of his most celebrated works include operas such as "Giulio Cesare" and "Rodelinda," as well as oratorios like "Messiah" and "Samson."

Handel''s arrival in England in 1710 marked a pivotal moment in his career. He quickly became one of the most sought-after composers in the country, composing numerous operas for the Royal Academy of Music. However, as the popularity of Italian opera waned, Handel turned his attention to oratorios, which became his primary focus. Among his most renowned oratorios, "Messiah" stands as a masterpiece that continues to be performed worldwide during the Christmas season. Handel''s music is characterized by its grandeur, melodic beauty, and expressive power. He had an uncanny ability to create memorable melodies and captivating harmonies, which are evident throughout his vast catalog of works.

Throughout his life, Handel enjoyed significant patronage from royalty and wealthy individuals, which enabled him to pursue his musical endeavors with both freedom and resources. Despite facing financial difficulties towards the end of his life, Handel''s legacy as one of the greatest composers of the Baroque era remains firmly established. His compositions continue to be performed and admired by audiences around the world, and his influence on subsequent generations of musicians cannot be overstated. Handel''s contributions to the world of music have left an indelible mark, and his name continues to be synonymous with musical excellence and innovation.'),
                                                                                                                                                                                      (208,	'Franz Joseph Haydn',	'https://assets.openopus.org/portraits/21056059-1568084909.jpg',	'Classical',	'1732-01-01 00:00:00',	'Rohrau, Austria',	'1809-01-01 00:00:00',	'Vienna, Austria',	NULL,	'Franz Joseph Haydn (1732-1809) was an Austrian composer who is widely considered to be the "father of the symphony" and the "father of the string quartet." He was a prolific composer, writing over 100 symphonies, 50 string quartets, and numerous other works. Haydn''s music is known for its wit, humor, and melodic beauty.',	'Franz Joseph Haydn was an Austrian composer of the Classical period, born in Rohrau, Lower Austria, on March 31, 1732. As the son of a wheelwright, he received limited formal education but displayed an early talent for music. At the age of six, he was sent to live with his uncle, Johann Matthias Frankh, who taught him the basics of music. In 1740, at the age of eight, he became a choirboy at the choir school of St. Stephen''s Cathedral in Vienna, where he studied under the direction of Georg Reutter the Younger, the cathedral''s Kapellmeister. Haydn''s musical education continued in earnest during his eight years at the choir school, where he studied composition, keyboard playing, and singing.

Haydn''s career as a composer began in earnest after he left the choir school in 1749. He initially worked as a freelance musician, composing and teaching music. In 1761, he secured a position as vice-Kapellmeister to Prince Paul Anton Esterházy, and in 1766, he became the full Kapellmeister, a post he held until 1790. During this time, Haydn composed a prolific amount of music, including symphonies, concertos, string quartets, and operas. He also oversaw the musical establishment of the Esterházy court, which was one of the most important musical centers in Europe at the time. Haydn''s music from this period is characterized by its wit, charm, and elegance, and it helped to establish the Classical style of music.

In 1791, Haydn visited England for the first time, where he was warmly received by the public and musicians alike. He composed some of his most famous works during this time, including the Symphony No. 94 ("Surprise") and the Symphony No. 104 ("London"). Haydn visited England again in 1794-1795, and after his return to Vienna, he composed some of his most ambitious works, including the oratorio The Creation and the Mass in Time of War. Haydn died in Vienna on May 31, 1809, and was buried in the Hundsturmer Friedhof. His music continues to be performed and enjoyed by audiences worldwide, and he is considered one of the greatest composers of all time.'),
                                                                                                                                                                                      (197,	'Franz Liszt',	'https://assets.openopus.org/portraits/60368090-1568084919.jpg',	'Romantic',	'1811-01-01 00:00:00',	'Doborján, Hungary',	'1886-01-01 00:00:00',	'Bayreuth, Germany',	NULL,	'Franz Liszt, a Hungarian virtuoso pianist and composer of the Romantic era, revolutionized piano technique and captivated audiences with his flamboyant performances. Known as the "Piano King," he composed numerous works, including the Hungarian Rhapsodies and the Faust Symphony.',	'Franz Liszt, born October 22, 1811, in Doborján, Hungary, was a virtuoso pianist, composer, teacher, and conductor. His remarkable talent and charisma left an indelible mark on the world of music, earning him the moniker "the Paganini of the piano." Liszt''s musical prowess was evident from a young age, and he quickly gained recognition as a child prodigy. At the age of 11, he embarked on a concert tour that catapulted him to international fame. Throughout his career, Liszt captivated audiences with his unparalleled technique, showmanship, and ability to evoke a wide range of emotions with his playing.

As a composer, Liszt''s innovative ideas and groundbreaking techniques pushed the boundaries of musical expression. He blended elements of romanticism, classical music, and Hungarian folk melodies, creating a distinctive and influential style. Liszt''s piano compositions, such as his Hungarian Rhapsodies and Transcendental Études, showcased his technical brilliance and expressive range. He also composed orchestral works, including the symphonic poems "Les Préludes" and "Tasso," which demonstrated his mastery of orchestration and his gift for evoking vivid imagery through music.

Beyond his musical achievements, Liszt was a humanitarian and a pioneer in the field of music education. He established the Liszt Institute in Weimar, Germany, which became a renowned center for musical instruction. Liszt''s generosity extended to supporting other musicians, and he played a pivotal role in the careers of composers like Richard Wagner and Edvard Grieg. In his later years, Liszt embraced a more religious lifestyle, devoting himself to composing sacred music and establishing a music academy in Rome. Franz Liszt''s legacy as a musical genius continues to inspire musicians and music lovers alike, leaving a lasting imprint on the world of classical music.'),
                                                                                                                                                                                      (77,	'Gustav Mahler',	'https://assets.openopus.org/portraits/22233485-1568084921.jpg',	'Late Romantic',	'1860-01-01 00:00:00',	'Kaliště, Bohemia',	'1911-01-01 00:00:00',	'Vienna, Austria',	NULL,	'Gustav Mahler (1860-1911) was an Austrian composer and conductor known for his complex and emotionally charged symphonies. His music often explored themes of love, loss, and the search for meaning in life.',	'Gustav Mahler (1860-1911) was an Austrian composer and conductor of the late Romantic period. Born in rural Bohemia into a large Jewish family, Mahler displayed musical talent from an early age. He studied piano and composition at the Vienna Conservatory and began his career as a conductor in various opera houses throughout Europe.

Mahler''s music is characterized by its grand scale, emotional intensity, and use of multiple movements. His symphonies are particularly known for their length and complexity, some lasting over an hour in performance. Mahler often incorporated elements of folk music, Jewish liturgical music, and vocal passages into his works, creating a unique and evocative musical language. His early symphonies, such as the "Titan" Symphony (No. 1) and the "Resurrection" Symphony (No. 2), are characterized by their programmatic nature and use of large orchestral forces. Later symphonies, such as the "Song of the Earth" (No. 8) and the "Symphony of a Thousand" (No. 8), are more introspective and philosophical, exploring themes of life, death, and spirituality.

Mahler''s conducting career is equally renowned. He is considered one of the greatest conductors of all time, known for his passionate and demanding interpretations of works by Wagner, Beethoven, and his own compositions. Mahler''s influence on subsequent generations of composers has been profound, and his music continues to be performed and admired worldwide. Among the many accolades he received during his lifetime, Mahler was appointed director of the Vienna Court Opera in 1897, a position he held until 1907. Despite his success, Mahler faced personal struggles and prejudice due to his Jewish heritage, which ultimately led to his resignation from the Vienna Opera. He died of a heart attack in 1911, leaving behind a legacy as one of the most significant composers of the late Romantic era.'),
                                                                                                                                                                                      (147,	'Felix Mendelssohn',	'https://assets.openopus.org/portraits/77325243-1568084923.jpg',	'Romantic',	'1809-01-01 00:00:00',	'Hamburg, Germany',	'1847-01-01 00:00:00',	'Leipzig, Germany',	NULL,	'Felix Mendelssohn (1809-1847) was a German composer, pianist, and conductor of the Romantic period. He is best known for his "Italian" and "Scottish" symphonies, and for his oratorio "Elijah."',	'Felix Mendelssohn-Bartholdy, born in Hamburg, Germany, on February 3, 1809, was a renowned composer, pianist, conductor, and organist. As a child prodigy, he began composing at an early age and gave public piano recitals by the age of nine. Mendelssohn''s early exposure to music and the arts was facilitated by his wealthy and cultured family, who provided him with an exceptional education. His father, Abraham Mendelssohn, was a successful banker, and his mother, Lea Salomon, was a talented pianist.

Throughout his career, Mendelssohn exhibited a remarkable versatility, excelling in various musical genres. He composed numerous symphonies, concertos, overtures, and chamber works. His most famous orchestral pieces include the "Italian" Symphony, the "Hebrides" Overture, and the "Violin Concerto in E minor." Mendelssohn''s piano works, such as the "Songs Without Words" and the "Variations Sérieuses," showcased his virtuosic technique and lyrical sensibilities. Additionally, he composed a significant body of choral music, including the oratorios "Elijah" and "St. Paul," which exemplify his mastery of large-scale choral forms.

Besides his compositional prowess, Mendelssohn was an accomplished pianist and conductor. He toured extensively throughout Europe, performing his own works and those of other composers. As a conductor, he led the Leipzig Gewandhaus Orchestra, one of the most prestigious musical institutions of its time. Mendelssohn''s interpretations were characterized by their clarity, precision, and emotional depth. He also played a pivotal role in the revival of interest in the music of Johann Sebastian Bach, whose works he performed and edited. Mendelssohn''s influence on subsequent generations of composers was profound, particularly in the Romantic era, and his music continues to be performed and enjoyed worldwide.'),
                                                                                                                                                                                      (196,	'Wolfgang Amadeus Mozart',	'https://assets.openopus.org/portraits/21459195-1568084925.jpg',	'Classical',	'1756-01-01 00:00:00',	'Salzburg, Austria',	'1791-01-01 00:00:00',	'Vienna, Austria',	NULL,	'Wolfgang Amadeus Mozart, a renowned Austrian composer of the classical period, is celebrated for his precocious talent, melodic genius, and compositional brilliance that transcends time. His timeless compositions, from operas like "The Marriage of Figaro" to symphonies like the "Jupiter Symphony," continue to captivate audiences worldwide.',	'Wolfgang Amadeus Mozart was an Austrian composer widely regarded as one of the greatest musical geniuses of all time. Born in Salzburg, Austria, on January 27, 1756, he displayed an extraordinary musical talent from his earliest years. At the tender age of six, he began composing and performing with his father, Leopold, and his sister, Maria Anna (Nannerl), embarking on a series of concert tours throughout Europe that astounded audiences with their virtuosity and precocity.

Mozart''s compositions encompassed a multitude of genres, including symphonies, concertos, operas, and chamber music. His early works, such as "Eine kleine Nachtmusik," showcased his mastery of melodic invention and rhythmic brilliance. In his later years, he produced monumental masterpieces like the opera "The Marriage of Figaro" and the unfinished Requiem Mass, demonstrating his unparalleled ability to blend sophistication, lyricism, and dramatic intensity. Mozart''s influence on subsequent generations of composers cannot be overstated. His innovative use of harmony and counterpoint, coupled with his gift for capturing human emotions and storytelling through music, has left an enduring legacy in the world of classical music.

Despite his immense talent and success, Mozart''s life was marked by financial struggles and personal tragedy. He died in Vienna on December 5, 1791, at the age of 35, with the exact cause of his death still a subject of speculation. Nevertheless, his music continues to enchant and inspire audiences worldwide, standing as a testament to his genius and the enduring power of artistic expression.'),
                                                                                                                                                                                      (146,	'Giacomo Puccini',	'https://assets.openopus.org/portraits/90175388-1568084932.jpg',	'Late Romantic',	'1858-01-01 00:00:00',	'Lucca, Italy',	'1924-01-01 00:00:00',	'Brussels, Belgium',	NULL,	'Giacomo Puccini (1858-1924) was an Italian composer known for his operas, including "La Bohème," "Tosca," and "Madama Butterfly." His works are characterized by their melodic beauty, dramatic intensity, and exploration of human emotions.',	'Giacomo Puccini, born December 22, 1858, in Lucca, Italy, was a towering figure in the world of opera. The great-grandson of a choirmaster and the son of a composer, Puccini''s musical lineage was evident from an early age. Despite his father''s aspirations for him to pursue a more practical career, Puccini''s passion for music prevailed, and he enrolled at the Milan Conservatory in 1880.

During his time at the conservatory, Puccini honed his craft under the guidance of Amilcare Ponchielli, a renowned composer of the time. Puccini''s talent was quickly recognized, and his early works, including "Le Villi" and "Edgar," showcased his innate melodic gift and dramatic flair. However, it was with his third opera, "Manon Lescaut" (1893), that Puccini achieved widespread acclaim. The opera''s heart-wrenching love story and sumptuous melodies captivated audiences, firmly establishing Puccini as a rising star in the operatic world.

Puccini''s subsequent operas, including "La Bohème" (1896), "Tosca" (1900), and "Madama Butterfly" (1904), solidified his position as one of the most celebrated composers of all time. These works, with their exquisite orchestrations, unforgettable characters, and soaring melodies, continue to be performed to sold-out houses worldwide. Puccini''s operas are renowned for their emotional intensity, their exploration of human relationships, and their ability to transcend cultural barriers and resonate with audiences of all generations.'),
                                                                                                                                                                                      (57,	'Maurice Ravel',	'https://assets.openopus.org/portraits/74628863-1568084938.jpg',	'Late Romantic',	'1875-01-01 00:00:00',	'Ciboure, France',	'1937-01-01 00:00:00',	'Paris, France',	NULL,	'Maurice Ravel, French composer and pianist known for his impressionistic and neoclassical works. His famous compositions include "Boléro," "Daphnis et Chloé," and "Piano Concerto in G Major."',	'Maurice Ravel, the acclaimed French composer renowned for his exquisite musical craftsmanship, emerged as one of the most influential figures in 20th-century classical music. Born in Ciboure, France, on March 7, 1875, Ravel displayed an exceptional musical talent from an early age. His father, an engineer, provided him with a stable upbringing, while his Basque mother instilled in him a lifelong appreciation for the region''s vibrant folk music. Ravel''s formative years were spent in Paris, where he studied at the prestigious Conservatoire de Paris under the tutelage of renowned teachers, including Gabriel Fauré.

Ravel''s compositional style was characterized by extraordinary precision, clarity, and attention to detail. He exhibited a remarkable ability to blend traditional forms with innovative harmonies and exotic rhythms. His music often evoked a sense of mystère and evoked both the past and the future. Ravel''s most famous works include the orchestral masterpiece "Boléro" (1928), the impressionistic piano suite "Miroirs" (1905), and the opera "L''Enfant et les Sortilèges" (1925). His music has been described as a combination of French elegance and Spanish passion, often employing sophisticated orchestral techniques and rich, layered textures.

Throughout his career, Ravel collaborated with renowned musicians and artists, including the writer Colette and the choreographer Serge Diaghilev. He traveled extensively, absorbing influences from various cultures, which he seamlessly incorporated into his compositions. Despite suffering from ill health in his later years, Ravel continued to compose until his death in Paris on December 28, 1937. His legacy lives on through his timeless and captivating music, which continues to enchant audiences worldwide.'),
                                                                                                                                                                                      (183,	'Franz Schubert',	'https://assets.openopus.org/portraits/91122704-1568084944.jpg',	'Early Romantic',	'1797-01-01 00:00:00',	'Vienna, Austria',	'1828-01-01 00:00:00',	'Vienna, Austria',	NULL,	'Franz Schubert was an Austrian composer of the early Romantic era. Despite his short life, he composed over 600 lieder, nine symphonies, and a large body of chamber and solo piano music. He is considered one of the greatest composers of the 19th century.',	'Franz  Peter Schubert,  born on January 31, 1797, was an Austrian composer who lived during the late Classical and early Romantic eras. Despite his short life, Schubert composed a vast body of work, including over 600 songs, nine symphonies, and numerous chamber and piano pieces. His music is characterized by its lyrical melodies, rich harmonies, and emotional depth. Schubert''s songs, or Lieder, are particularly notable for their expressive and poetic qualities, and he is considered one of the greatest composers of Lieder in history.

Schubert''s early musical education began at a young age, and he displayed a prodigious talent for composition from an early age. He studied music at the Imperial Court Chapel in Vienna and later became a teacher and freelance composer. Schubert never held a full-time position as a musician, and he often struggled financially. Despite these challenges, he continued to compose prolifically, producing some of his most famous works, including the "Unfinished" Symphony, the "Trout" Quintet, and the song "Erlkönig."

Schubert died tragically at the age of 31 from complications of syphilis. His death was a great loss to the musical world, and he remains one of the most celebrated and beloved composers of all time. His music continues to be performed and recorded around the world, and he is considered one of the most important figures in the history of Western music.'),
                                                                                                                                                                                      (129,	'Robert Schumann',	'https://assets.openopus.org/portraits/25233320-1568084946.jpg',	'Romantic',	'1810-01-01 00:00:00',	'Zwickau, Germany',	'1856-01-01 00:00:00',	'Endenich, Bonn, Prussia',	NULL,	'Robert Schumann was a renowned German composer, music critic, and conductor of the Romantic era. Known for his passionate and introspective works, he made significant contributions to piano literature and song cycles. His marriage to the virtuoso pianist Clara Wieck played a pivotal role in his artistic and personal life.',	'Robert Schumann, a towering figure in the Romantic era of music, was born on June 8, 1810, in Zwickau, Germany. From an early age, he exhibited a prodigious talent for music, particularly piano playing. His father, a bookseller, encouraged Robert''s musical aspirations, providing him with a solid musical education. However, Schumann''s desire to pursue a career in music faced resistance from his father, who envisioned a more conventional path for his son, such as law or commerce.

Despite his father''s initial reluctance, Schumann''s unwavering passion for music prevailed. He broke away from the traditional educational path and immersed himself in the world of music. He studied with renowned pianists, including Friedrich Wieck, and diligently practiced to hone his virtuosic skills. However, an overzealous practice regimen led to a severe injury to his right hand, prematurely ending his hopes of a career as a concert pianist. Undeterred by this setback, Schumann turned his attention to composition.

Schumann''s musical language was characterized by its rich harmonic textures, lyrical melodies, and innovative forms. He defied conventional boundaries, experimenting with novel compositional techniques and pushing the limits of musical expression. His works spanned a wide range of genres, including symphonies, chamber music, piano pieces, and lieder (art songs). Schumann''s music is known for its emotional depth, poetic sensitivity, and the vivid storytelling that unfolds within its musical narratives. His profound understanding of human emotions and his ability to translate them into musical form established him as one of the most influential and revered composers of the Romantic era.'),
                                                                                                                                                                                      (165,	'Johann Strauss Jr',	'https://assets.openopus.org/portraits/93853123-1568084951.jpg',	'Romantic',	'1825-01-01 00:00:00',	'Vienna, Austria',	'1899-01-01 00:00:00',	'Vienna, Austria',	NULL,	'Johann Strauss Jr., the "Waltz King," was an Austrian composer famous for his captivating waltzes, operettas, and polkas. His melodies, filled with charm and elegance, have become beloved around the world and continue to mesmerize audiences to this day.',	'Johann Strauss Jr. (1825-1899), also known as the "Waltz King," was an Austrian composer who revolutionized the genre of dance music. Born into a musical family, he initially followed in his father''s footsteps by pursuing a career as a violinist. However, his true calling lay in composition, and he soon rose to prominence for his enchanting waltzes, which captivated audiences worldwide. Strauss Jr. possessed an extraordinary gift for creating unforgettable melodies, characterized by their rhythmic vitality, infectious charm, and soaring lyrical beauty. His works, such as "The Blue Danube," "Tales from the Vienna Woods," and "Emperor Waltz," became synonymous with the splendor and elegance of the Viennese court.

Strauss Jr. not only composed waltzes but also expanded his repertoire to include operettas, polkas, and other popular dance forms. His operettas, such as "Die Fledermaus" and "Der Zigeunerbaron," showcased his flair for witty dialogue, satirical humor, and vibrant musicality. Strauss Jr.''s music became the soundtrack to Vienna''s "Golden Age," a period of cultural and social transformation. His concerts at the Musikverein and the Hofburg Palace were legendary, attracting audiences from all walks of life who flocked to hear the intoxicating rhythms and melodies that became the embodiment of Viennese joie de vivre.

Strauss Jr.''s compositions transcended the boundaries of time and culture, becoming timeless classics that continue to be performed and enjoyed by audiences around the world. His legacy as the "Waltz King" remains uncontested, and his music serves as a testament to the enduring power of artistic brilliance. Strauss Jr.''s waltzes have become the epitome of elegance and refinement, capturing the essence of romance, nostalgia, and the celebration of life. His music continues to inspire and uplift, transporting listeners to a world of enchantment and timeless beauty.'),
                                                                                                                                                                                      (190,	'Igor Stravinsky',	'https://assets.openopus.org/portraits/84229197-1568084952.jpg',	'20th Century',	'1882-01-01 00:00:00',	'Oranienbaum, Russia',	'1971-01-01 00:00:00',	'New York City, USA',	NULL,	'Igor Stravinsky, a Russian-born composer, revolutionized classical music with his groundbreaking works like "The Rite of Spring" and "Petrushka." Known for his innovative use of rhythm and polytonality, he influenced generations of musicians and remains a towering figure in 20th-century music.',	'Igor Fyodorovich Stravinsky was a Russian-born composer, pianist, and conductor. He is considered one of the most influential composers of the 20th century. Stravinsky''s music is characterized by its rhythmic complexity, harmonic dissonance, and innovative use of instrumentation. He is best known for his ballets, including "The Firebird" (1910), "Petrushka" (1911), and "The Rite of Spring" (1913). Stravinsky also wrote operas, concertos, and chamber music.

Stravinsky was born in Oranienbaum, Russia, in 1882. He studied music at the St. Petersburg Conservatory. After graduating, he worked as a conductor and composer in Russia. In 1910, he met the impresario Sergei Diaghilev, who commissioned him to write "The Firebird" for the Ballets Russes. The success of "The Firebird" led to Stravinsky''s association with the Ballets Russes for many years.

In 1920, Stravinsky left Russia and settled in France. He became a French citizen in 1934. Stravinsky continued to compose music throughout his life. He died in New York City in 1971. Stravinsky''s music has had a profound influence on composers of the 20th and 21st centuries. His works are performed regularly by orchestras and ballet companies around the world.'),
                                                                                                                                                                                      (79,	'Pyotr Ilyich Tchaikovsky',	'https://assets.openopus.org/portraits/32941433-1568084956.jpg',	'Romantic',	'1840-01-01 00:00:00',	'Votkinsk, Russia',	'1893-01-01 00:00:00',	'Saint Petersburg, Russia',	NULL,	'Pyotr Ilyich Tchaikovsky was a renowned Russian composer of the Romantic era, known for his emotional melodies, orchestration mastery, and contributions to ballet music. His famous works include "Swan Lake," "The Nutcracker," and "1812 Overture."',	'Pyotr Ilyich Tchaikovsky was a towering figure in Russian music, renowned for his exceptional talent and enduring impact on classical composition. Born in Votkinsk, Russia, on May 7, 1840, he displayed an early affinity for music, beginning piano lessons at a young age. His formal musical education at the St. Petersburg Conservatory shaped his musical sensibilities, blending the technical rigor of Western European traditions with the melodic richness of Russian folk music.

Tchaikovsky''s career blossomed with the premiere of his First Symphony, "Winter Dreams," in 1866. This work signaled his mastery of orchestral composition and established him as a rising star in the Russian musical landscape. Subsequent masterpieces, including his ballets "Swan Lake" and "The Nutcracker," continue to captivate audiences worldwide. Tchaikovsky''s musical style is characterized by its emotional depth, lyrical melodies, and sweeping orchestral textures. His compositions often evoke a sense of grandeur and nostalgia, portraying the breadth of human emotions from love and joy to despair and longing.

Beyond his musical brilliance, Tchaikovsky''s legacy extends to his contributions as a conductor and music educator. As a conductor, he championed Russian music and introduced Western works to Russian audiences. His teaching at the Moscow Conservatory nurtured generations of young musicians, many of whom went on to become prominent figures in the classical music world. Tchaikovsky''s untimely death in 1893 at the age of 53 was a profound loss to the world of music, but his immense body of work continues to resonate with listeners and inspire countless musicians to this day.'),
                                                                                                                                                                                      (35,	'Giuseppe Verdi',	'https://assets.openopus.org/portraits/20193752-1568084957.jpg',	'Romantic',	'1813-01-01 00:00:00',	'Le Roncole, Busseto, Duchy of Parma (present-day Italy)',	'1901-01-01 00:00:00',	'Milan, Italy',	NULL,	'Giuseppe Verdi, an eminent Italian composer of the 19th century. Born in a humble village, his operas, such as "Aida" and "La Traviata," captivated audiences globally, showcasing his exceptional musicality and the power of dramatic storytelling.',	'Giuseppe Verdi, born in 1813 in Le Roncole, Italy, is widely regarded as one of the greatest composers of all time. His operas, characterized by their dramatic intensity, lush melodies, and powerful orchestrations, have captivated audiences worldwide for over a century. Verdi''s early life was marked by struggle and poverty, but his unwavering determination and exceptional musical talent led him to pursue a career in music. After studying at the Milan Conservatory, he made his operatic debut in 1839 with "Oberto, Conte di San Bonifacio."

Throughout his illustrious career, Verdi composed over 28 operas, each bearing the stamp of his unmistakable musical genius. "Nabucco" (1842) catapulted him to international fame and established him as a master of the Italian operatic tradition. His subsequent works, such as "Rigoletto" (1851), "La Traviata" (1853), and "Aida" (1871), became cornerstones of the operatic repertoire and epitomize Verdi''s ability to combine soaring melodies with heart-wrenching drama. Verdi''s operas not only showcased his musical brilliance but also reflected the social and political upheavals of his time. He was deeply involved in the Italian Risorgimento, a movement advocating for Italian unification, and infused his music with patriotic themes. His opera "Il Trovatore" (1853), with its powerful chorus, became an anthem for the Italian struggle for independence.

Beyond his operatic triumphs, Verdi also composed a Requiem Mass (1874) in memory of the Italian writer Alessandro Manzoni. This monumental work, characterized by its grandeur and emotional intensity, stands as a testament to Verdi''s versatility as a composer. Verdi''s legacy extends far beyond his own lifetime, with his operas continuing to be performed and enjoyed by audiences around the world. His exceptional musical talent, coupled with his unwavering determination and ability to convey deep human emotions through music, solidifies his place as one of the most influential and celebrated composers in history.'),
                                                                                                                                                                                      (98,	'Antonio Vivaldi',	'https://assets.openopus.org/portraits/64540242-1568084959.jpg',	'Baroque',	'1678-01-01 00:00:00',	'Venice, Republic of Venice',	'1741-01-01 00:00:00',	'Vienna, Austria',	NULL,	'Antonio Vivaldi, a renowned Baroque era composer, was a virtuoso violinist and an innovative musical genius. His iconic work, "The Four Seasons," showcases his masterful use of harmony, melody, and orchestral color.',	'Antonio Vivaldi, the renowned Italian Baroque composer, was born in Venice on March 4, 1678. A virtuoso violinist and talented composer, Vivaldi became known for his groundbreaking contributions to the genre. Known as the "Red Priest" due to his fiery hair and cloth, Vivaldi was ordained as a Catholic priest in 1703. Despite his priestly vows, he maintained a passionate involvement in music, composing over 500 concertos, 46 operas, and numerous other sacred and secular works.

Throughout his life, Vivaldi held various musical positions, including maestro di violino at the Ospedale della Pietà, a renowned musical institution in Venice. Here, he nurtured the talents of young female musicians, composing numerous concertos and other works tailored to their abilities. Vivaldi''s music is characterized by its brilliance, virtuosity, and emotional intensity. He mastered the use of harmonic patterns, melodic ornamentation, and complex rhythms, creating an innovative and vibrant musical style. His concertos, particularly his "The Four Seasons," remain among the most popular and widely performed classical works today.

Antonio Vivaldi''s influence on music cannot be overstated. He played a pivotal role in the development of the Baroque concerto and significantly contributed to the rise of instrumental music as an independent form of artistic expression. His ability to blend technical prowess with emotional sensitivity made him one of the most celebrated composers of his time. Vivaldi''s legacy continues to inspire and captivate audiences worldwide, his music transcending the boundaries of time to touch the hearts and minds of music lovers across generations.'),
                                                                                                                                                                                      (138,	'Richard Wagner',	'https://assets.openopus.org/portraits/39267138-1568084959.jpg',	'Romantic',	'1813-01-01 00:00:00',	'Leipzig, Saxony, Germany',	'1883-01-01 00:00:00',	'Venice, Italy',	NULL,	'Richard Wagner (1813-1883) was a renowned German composer, conductor, and theorist. He is celebrated for his groundbreaking operas, including the "Ring" cycle and "Tristan und Isolde," which are characterized by their complex harmonies, leitmotifs, and philosophical themes.',	'Richard Wagner (1813-1883) was an influential German composer, conductor, playwright, and theater director. He is best known for his operas, which have had a profound impact on the history of music. Wagner''s music is characterized by its rich, Romantic harmonies, complex orchestration, and innovative use of leitmotifs—musical themes associated with specific characters, objects, or ideas.

Wagner''s operas are often epic in scale and scope, and they typically deal with themes of love, loss, and redemption. Some of his most famous works include the Ring Cycle (a four-part opera based on Norse mythology), Tristan und Isolde, and Parsifal. Wagner''s operas were often controversial in their day, due to their length, complexity, and use of unconventional harmonies. However, they eventually gained widespread acceptance and are now considered to be among the greatest masterpieces of Western music.

Wagner was also a prolific writer, and he published numerous essays and treatises on music and drama. In his writings, Wagner advocated for the Gesamtkunstwerk, or "total artwork," in which all of the elements of the opera—music, drama, and visual arts—are seamlessly integrated to create a unified artistic experience. Wagner''s ideas about the Gesamtkunstwerk have had a profound influence on subsequent generations of composers and theater directors.');