services:
  cache:
    image: redis:6.2-alpine
    restart: always
    expose:
      - 6379
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
  db:
    image: postgres:12
    expose:
      - 5432
    restart: always
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - POSTGRES_DB=${POSTGRES_DB?Variable not set}

  adminer:
    image: adminer
    restart: always
    expose:
      - 8080:8080
    depends_on:
      - db
    environment:
      - ADMINER_DESIGN=pepa-linha-dark
    labels: # new
      - "traefik.enable=true"
      - "traefik.http.routers.adminer.rule=Host(`adminer.localhost.com`)"
      - "traefik.http.services.adminer.loadbalancer.server.port=8080"

  backend:
    image: '${DOCKER_IMAGE_BACKEND?Variable not set}:${TAG-latest}'
    expose:
      - 8000
    restart: always
    depends_on:
      - db
      - cache
      - meilisearch
    env_file:
      - .env
    environment:
      - DOMAIN=${DOMAIN}
      - ENVIRONMENT=${ENVIRONMENT}
      - BACKEND_CORS_ORIGINS=${BACKEND_CORS_ORIGINS}
      - SECRET_KEY=${SECRET_KEY?Variable not set}
      - POSTGRES_SERVER=db
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
      - REDIS_HOST=${REDIS_HOST?Variable not set}
      - REDIS_PORT=${REDIS_PORT?Variable not set}
      - REDIS_PASSWORD=${REDIS_PASSWORD?Variable not set}
    labels: # new
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi.rule=Host(`api.localhost.com`)"
      - "traefik.http.services.backend.loadbalancer.server.port=8000"

    build:
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}
    # platform: linux/amd64

  traefik: # new
    image: traefik:v2.9.6
    ports:
      - 80:80
      - 8081:8080
    volumes:
      - "./traefik.dev.toml:/etc/traefik/traefik.toml"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  meilisearch:
    image: getmeili/meilisearch:v1.1.1
    volumes:
      - ./data.ms:/data.ms
    ports:
      - 7700:7700
    environment:
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY:-ms}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:7700" ]
      interval: 10s
      timeout: 5s
      retries: 5
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.meilisearch.rule=Host(`meili.localhost.com`)"
      - "traefik.http.services.meilisearch.loadbalancer.server.port=7700"