# traefik.prod.toml

[entryPoints]
[entryPoints.web]
address = ":80"
[entryPoints.web.http]
[entryPoints.web.http.redirections]
[entryPoints.web.http.redirections.entryPoint]
to = "websecure"
scheme = "https"

[entryPoints.websecure]
address = ":443"

[accessLog]

[api]
dashboard = true

[providers]
[providers.docker]
exposedByDefault = false

[certificatesResolvers.letsencrypt.acme]
email = "jacopo.beragnoli@edu.unifi.it"
[certificatesResolvers.letsencrypt.acme.httpChallenge]
entryPoint = "web"
[[tls.certificates]]
certFile = "/traefik-public-certificates/fullchain.pem"
keyFile = "/traefik-public-certificates/privkey.pem"