import type { NextPage } from 'next'
import Head from 'next/head'
import LoginButton from '../components/LoginButton'
import { useWindowSize } from '../utils/useWindowSize'
import { useSession } from 'next-auth/react'
import { useEffect } from 'react'
import { useRouter } from 'next/router'
import { Box } from '@chakra-ui/react'

const Home: NextPage = () => {
  const size = useWindowSize()
  const router = useRouter()
  const { data: session } = useSession()

  if (session) {
    router.push('/home')
  }

  return (
    <Box>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </Box>
  )
}

export default Home
